Update prompt

diff --git a/.bash/prompt b/.bash/prompt
--- a/.bash/prompt
+++ b/.bash/prompt
@@ -1,55 +1,76 @@
-# @gf3’s Sexy Bash Prompt, inspired by “Extravagant Zsh Prompt”
-# Shamelessly copied from https://github.com/gf3/dotfiles
-# Screenshot: http://i.imgur.com/s0Blh.png
 
-if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
-	export TERM=gnome-256color
-elif infocmp xterm-256color >/dev/null 2>&1; then
-	export TERM=xterm-256color
-fi
+__powerline() {
 
-if tput setaf 1 &> /dev/null; then
-	tput sgr0
-	if [[ $(tput colors) -ge 256 ]] 2>/dev/null; then
-		MAGENTA=$(tput setaf 9)
-		ORANGE=$(tput setaf 172)
-		GREEN=$(tput setaf 190)
-		PURPLE=$(tput setaf 141)
-		WHITE=$(tput setaf 0)
-	else
-		MAGENTA=$(tput setaf 5)
-		ORANGE=$(tput setaf 4)
-		GREEN=$(tput setaf 2)
-		PURPLE=$(tput setaf 1)
-		WHITE=$(tput setaf 7)
-	fi
-	BOLD=$(tput bold)
-	RESET=$(tput sgr0)
-else
-	MAGENTA="\033[1;31m"
-	ORANGE="\033[1;33m"
-	GREEN="\033[1;32m"
-	PURPLE="\033[1;35m"
-	WHITE="\033[1;37m"
-	BOLD=""
-	RESET="\033[m"
-fi
+    # Unicode symbols
+    readonly PS_SYMBOL_DARWIN=''
+    readonly PS_SYMBOL_LINUX='$'
+    readonly PS_SYMBOL_OTHER='%'
+    readonly GIT_BRANCH_SYMBOL='⑂ '
+    readonly GIT_BRANCH_CHANGED_SYMBOL='+'
+    readonly GIT_NEED_PUSH_SYMBOL='⇡'
+    readonly GIT_NEED_PULL_SYMBOL='⇣'
 
-export MAGENTA
-export ORANGE
-export GREEN
-export PURPLE
-export WHITE
-export BOLD
-export RESET
+    readonly FG_RED="\[$(tput setaf 1)\]"
+    readonly FG_GREEN="\[$(tput setaf 7)\]"
 
-function parse_git_dirty() {
-	[[ $(git status 2> /dev/null | tail -n1) != *"working directory clean"* ]] && echo "*"
+    readonly FG_PROMPT="\[$(tput setaf 11)\]"
+    readonly FG_GIT="\[$(tput setaf 13)\]"
+
+    readonly DIM="\[$(tput dim)\]"
+    readonly REVERSE="\[$(tput rev)\]"
+    readonly RESET="\[$(tput sgr0)\]"
+    readonly BOLD="\[$(tput bold)\]"
+
+    # what OS?
+    case "$(uname)" in
+        Darwin)
+            readonly PS_SYMBOL=$PS_SYMBOL_DARWIN
+            ;;
+        Linux)
+            readonly PS_SYMBOL=$PS_SYMBOL_LINUX
+            ;;
+        *)
+            readonly PS_SYMBOL=$PS_SYMBOL_OTHER
+    esac
+
+    __git_info() { 
+        [ -x "$(which git)" ] || return    # git not found
+
+        # get current branch name or short SHA1 hash for detached head
+        local branch="$(git symbolic-ref --short HEAD 2>/dev/null || git describe --tags --always 2>/dev/null)"
+        [ -n "$branch" ] || return  # git branch not found
+
+        local marks
+
+        # branch is modified?
+        [ -n "$(git status --porcelain)" ] && marks+=" $GIT_BRANCH_CHANGED_SYMBOL"
+
+        # how many commits local branch is ahead/behind of remote?
+        local stat="$(git status --porcelain --branch | grep '^##' | grep -o '\[.\+\]$')"
+        local aheadN="$(echo $stat | grep -o 'ahead \d\+' | grep -o '\d\+')"
+        local behindN="$(echo $stat | grep -o 'behind \d\+' | grep -o '\d\+')"
+        [ -n "$aheadN" ] && marks+=" $GIT_NEED_PUSH_SYMBOL$aheadN"
+        [ -n "$behindN" ] && marks+=" $GIT_NEED_PULL_SYMBOL$behindN"
+
+        # print the git branch segment without a trailing newline
+        printf " $GIT_BRANCH_SYMBOL$branch$marks "
+    }
+
+    ps1() {
+        # Check the exit code of the previous command and display different
+        # colors in the prompt accordingly. 
+        if [ $? -eq 0 ]; then
+            local BG_EXIT="$FG_GREEN"
+        else
+            local BG_EXIT="$FG_RED"
+        fi
+
+        PS1="$BG_EXIT>$FG_PROMPT \w $RESET"
+        PS1+="$FG_GIT$(__git_info)$RESET"
+    }
+
+    PROMPT_COMMAND=ps1
 }
 
-function parse_git_branch() {
-	git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
-}
-
-export PS1="\[${BOLD}${MAGENTA}\]\u \[$WHITE\]at \[$ORANGE\]\h \[$WHITE\]in \[$GREEN\]\w\[$WHITE\]\$([[ -n \$(git branch 2> /dev/null) ]] && echo \" on \")\[$PURPLE\]\$(parse_git_branch)\[$WHITE\]\n\$ \[$RESET\]"
-export PS2="\[$ORANGE\]→ \[$RESET\]"
+__powerline
+unset __powerline
